/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3D-room.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D-room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['G-table-3'].geometry} material={materials['[Formica Laminate Light]']} position={[1.409, 0.727, -4.1]} rotation={[0, 0.244, 0]} />
      <mesh geometry={nodes['G-table-2'].geometry} material={materials['[Formica Laminate Light]']} position={[1.109, 0.727, -2.376]} rotation={[0, 0.244, 0]} />
      <mesh geometry={nodes['G-table-1'].geometry} material={materials['[Formica Laminate Light]']} position={[3.05, 0.727, -2.86]} rotation={[0, 0.244, 0]} />
      <mesh geometry={nodes['G-floor'].geometry} material={materials.Material} position={[4.335, 0.15, -4.09]} />
      <mesh geometry={nodes['G-column-1'].geometry} material={materials.Material} position={[8.495, 1.8, -0.125]} />
      <mesh geometry={nodes['G-column-2'].geometry} material={materials.Material} position={[4.335, 1.8, -0.125]} />
      <mesh geometry={nodes['G-column-5'].geometry} material={materials.Material} position={[0.175, 1.8, -8.055]} />
      <mesh geometry={nodes['G-column-4'].geometry} material={materials.Material} position={[0.175, 1.8, -4.09]} />
      <mesh geometry={nodes['G-column-6'].geometry} material={materials.Material} position={[4.335, 1.8, -8.055]} />
      <mesh geometry={nodes['G-column-8'].geometry} material={materials.Material} position={[8.495, 1.8, -4.09]} />
      <mesh geometry={nodes['G-column-3'].geometry} material={materials.Material} position={[0.175, 1.8, -0.125]} />
      <mesh geometry={nodes['G-column-7'].geometry} material={materials.Material} position={[8.495, 1.8, -8.055]} />
      <group position={[0.949, 0.731, -2.963]}>
        <mesh geometry={nodes['G-chair-1_1'].geometry} material={materials.CP_B} />
        <mesh geometry={nodes['G-chair-1_2'].geometry} material={materials['*2']} />
        <mesh geometry={nodes['G-chair-1_3'].geometry} material={materials.casters} />
        <mesh geometry={nodes['G-chair-1_4'].geometry} material={materials['*6']} />
        <mesh geometry={nodes['G-chair-1_5'].geometry} material={materials['*1']} />
      </group>
      <group position={[2.838, 0.731, -3.406]}>
        <mesh geometry={nodes['G-chair-2_1'].geometry} material={materials.CP_B} />
        <mesh geometry={nodes['G-chair-2_2'].geometry} material={materials['*2']} />
        <mesh geometry={nodes['G-chair-2_3'].geometry} material={materials.casters} />
        <mesh geometry={nodes['G-chair-2_4'].geometry} material={materials['*6']} />
        <mesh geometry={nodes['G-chair-2_5'].geometry} material={materials['*1']} />
      </group>
      <group position={[1.317, 0.731, -4.69]}>
        <mesh geometry={nodes['G-chair-3_1'].geometry} material={materials.CP_B} />
        <mesh geometry={nodes['G-chair-3_2'].geometry} material={materials['*2']} />
        <mesh geometry={nodes['G-chair-3_3'].geometry} material={materials.casters} />
        <mesh geometry={nodes['G-chair-3_4'].geometry} material={materials['*6']} />
        <mesh geometry={nodes['G-chair-3_5'].geometry} material={materials['*1']} />
      </group>
      <group position={[2.322, 1.725, -1.052]}>
        <mesh geometry={nodes['G-TV_1'].geometry} material={materials.TV} />
        <mesh geometry={nodes['G-TV_2'].geometry} material={materials['[Aluminum]']} />
      </group>
      <group position={[3.043, 1.214, -2.895]}>
        <mesh geometry={nodes['G-com-1_1'].geometry} material={materials['all metal']} />
        <mesh geometry={nodes['G-com-1_2'].geometry} material={materials.Color_009} />
        <mesh geometry={nodes['G-com-1_3'].geometry} material={materials.Color_000} />
        <mesh geometry={nodes['G-com-1_4'].geometry} material={materials.Color_1} />
        <mesh geometry={nodes['G-com-1_5'].geometry} material={materials.Translucent_Glass_Gray} />
      </group>
      <group position={[1.157, 1.214, -2.331]}>
        <mesh geometry={nodes['G-com-2_1'].geometry} material={materials['all metal']} />
        <mesh geometry={nodes['G-com-2_2'].geometry} material={materials.Color_009} />
        <mesh geometry={nodes['G-com-2_3'].geometry} material={materials.Color_1} />
        <mesh geometry={nodes['G-com-2_4'].geometry} material={materials.Color_000} />
        <mesh geometry={nodes['G-com-2_5'].geometry} material={materials.Translucent_Glass_Gray} />
      </group>
      <group position={[1.502, 1.214, -4.085]}>
        <mesh geometry={nodes['G-com-3_1'].geometry} material={materials['all metal']} />
        <mesh geometry={nodes['G-com-3_2'].geometry} material={materials.Color_009} />
        <mesh geometry={nodes['G-com-3_3'].geometry} material={materials.Color_000} />
        <mesh geometry={nodes['G-com-3_4'].geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes['G-com-3_5'].geometry} material={materials.Color_1} />
      </group>
      <mesh geometry={nodes['G-server-1'].geometry} material={materials['[Formica Laminate Dark]']} position={[5.174, 1.237, -1.505]} />
      <mesh geometry={nodes['G-server-2'].geometry} material={materials['[Formica Laminate Dark]']} position={[6.274, 1.237, -1.505]} />
      <mesh geometry={nodes['G-wall-1'].geometry} material={materials.Material} position={[5.915, 1.8, -0.05]} />
      <mesh geometry={nodes['G-wall-2'].geometry} material={materials.Material} position={[2.255, 1.8, -0.05]} />
      <mesh geometry={nodes['G-wall-3'].geometry} material={materials.Material} position={[6.415, 1.8, -8.055]} />
      <mesh geometry={nodes['G-wall-4'].geometry} material={materials.Material} position={[2.255, 1.8, -8.055]} />
      <mesh geometry={nodes['G-wall_glass-1'].geometry} material={materials['[Translucent Glass Blue]']} position={[0.025, 1.8, -2.107]} />
      <mesh geometry={nodes['G-wall_glass-2'].geometry} material={materials['[Translucent Glass Blue]']} position={[8.345, 1.8, -2.107]} />
      <mesh geometry={nodes['G-wall_glass-3'].geometry} material={materials['[Translucent Glass Blue]']} position={[8.345, 1.8, -6.073]} />
      <mesh geometry={nodes['G-wall_glass-4'].geometry} material={materials['[Translucent Glass Blue]']} position={[7.795, 1.8, 0.025]} />
      <mesh geometry={nodes['G-wall_glass-5'].geometry} material={materials['[Translucent Glass Blue]']} position={[0.025, 1.8, -5.597]} />
      <mesh geometry={nodes['G-wall_glass-6'].geometry} material={materials['[Translucent Glass Blue]']} position={[0.076, 1.8, -7.415]} />
    </group>
  )
}

useGLTF.preload('/3D-room.glb')
