import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo Room 3D',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-stone-800 border-gray-800`}>
        <main className="p-0">
          {children}
        </main>
      </body>
    </html>
  )
}
