import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo Room 3D',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-4">
          <div className="mb-6 rounded-md border-2 bg-stone-800 border-gray-800 p-6">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
