/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dModel/kitchen/scene.gltf 
Author: Tsybe (https://sketchfab.com/imtsybe)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cartoon-kitchen-interior-b42fec3f1fd44894b3a032e8a844ab90
Title: Cartoon Kitchen Interior
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useControls, folder } from 'leva'
import { Select } from '@react-three/postprocessing'

export function Kitchen(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/3dModel/kitchen/scene.gltf")
  const { ref, actions, names } = useAnimations(animations, group)
  const [hover, setHover] = useState()
  // const [obj, setObj] = useState({
  //   all: false,
  //   chair1: false,
  //   chair2: false,
  //   chair3: false,
  //   chair4: false,
  //   chair5_6: false,
  // })

  const obj = useControls({
    all: { value: false },
    parts: folder(
      {
        chair1: { value: false },
        chair2: { value: false },
        chair3: { value: false },
        chair4: { value: false },
        chair5_6: { value: false },
      },
      { collapsed: true },
    ),
  })

  useEffect(() => {
    const playAnimation = async () => {
      // Assuming 'play' is the name of your animation action
      const animationAction = actions[names].play();

      animationAction.repetitions = 1;

      // Play the animation for 2 seconds
      await new Promise(resolve => setTimeout(resolve, 3000));

      // Set the time scale to 0 to effectively pause the animation
      animationAction.setEffectiveTimeScale(0);
    };

    playAnimation();
  }, [actions]);

  return (
    <group onPointerOver={(e) => setHover(e.object.parent.name)} onPointerOut={(e) => setHover(null)} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <Select enabled={obj.all}>
                <group name="ToolHolder_14" position={[3.919, 21.633, -2.739]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.ToolHolder} />
                </group>
                <group name="Tool#3_15" position={[3.892, 21.627, -2.886]}>
                  <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Tool3.001']} />
                </group>
                <group name="Tool#2_16" position={[3.892, 21.627, -2.69]}>
                  <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Tool2.001']} />
                </group>
                <group name="Tool#1_17" position={[3.892, 21.627, -2.593]}>
                  <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Tool1.001']} />
                </group>
                <group name="Toaster_18" position={[-0.218, 20.962, -4.065]} rotation={[0, -0.293, 0]}>
                  <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Toaster} />
                </group>
                <group name="Teapot_19" position={[0.623, 20.962, -4.114]} rotation={[0, 1.519, 0]}>
                  <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Teapot} />
                </group>
                <group name="Table_20" position={[-0.11, 20, -0.63]}>
                  <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Table} />
                </group>
                <group name="Socket_ToasterHandle_22" position={[-0.319, 21.129, -3.991]}>
                  <group name="ToasterHandle_21" position={[0.075, -0.167, -0.1]}>
                    <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Toaster} />
                  </group>
                </group>
                <group name="Socket_ToasterBreadRear_24" position={[-0.221, 21.183, -4.087]}>
                  <group name="ToasterBreadRear_23" position={[0, -0.221, 0.02]}>
                    <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Toaster} />
                  </group>
                </group>
                <group name="Socket_ToasterBreadFront_26" position={[-0.221, 21.183, -4.045]}>
                  <group name="ToasterBreadFront_25" position={[0, -0.221, -0.02]}>
                    <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Toaster} />
                  </group>
                </group>
                <group name="Socket_Teapot_28" position={[0.623, 21.206, -4.114]}>
                  <group name="TeapotCover_27" position={[0, -0.244, 0]}>
                    <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Teapot} />
                  </group>
                </group>
                <group name="Socket_Pot_30" position={[3.622, 21.232, -1.47]}>
                  <group name="PotCover_29" position={[0, -0.258, 0]}>
                    <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material} />
                  </group>
                </group>
                <group name="Socket_Pot#2_32" position={[3.611, 21.304, -2.325]}>
                  <group name="Pot#2Cover_31" position={[0, -0.342, 0]}>
                    <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Pot2} />
                  </group>
                </group>
                <group name="Socket_OvenPlate_34" position={[3.385, 20.418, -1.637]}>
                  <group name="OvenPlate_33" position={[0, -0.418, -0.526]}>
                    <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Oven} />
                  </group>
                </group>
                <group name="Socket_OvenDoor_36" position={[3.02, 20.1, -1.637]}>
                  <group name="OvenDoor_35" position={[0, -0.1, -0.891]}>
                    <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.Oven} />
                  </group>
                </group>
                <group name="Socket_Microwave_38" position={[3.052, 21.176, -4.028]}>
                  <group name="Socket_MicrowaveDoor_37" position={[0.378, -0.214, -0.367]}>
                    <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Microwave} />
                  </group>
                </group>
                <group name="Socket_HorizontalUpperU_40" position={[2.486, 22.572, -3.537]}>
                  <group name="HorizontalUpperU_39" position={[0, -0.822, -0.886]}>
                    <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Horizontal.Upper']} />
                  </group>
                </group>
                <group name="Socket_HorizontalUpperL_42" position={[2.486, 22.186, -3.537]}>
                  <group name="HorizontalUpperL_41" position={[0, -0.436, -0.886]}>
                    <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials['Horizontal.Upper']} />
                  </group>
                </group>
                <group name="Socket_FridgeDoorU_44" position={[2.291, 21.267, 1.874]}>
                  <group name="FridgeDoorU_43" position={[-0.418, -1.267, -0.749]}>
                    <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Fridge} />
                  </group>
                </group>
                <group name="Socket_FridgeDoorL_46" position={[2.291, 20.485, 1.874]}>
                  <group name="FridgeDoorL_45" position={[-0.418, -0.485, -0.749]}>
                    <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Fridge} />
                  </group>
                </group>
                <group name="Socket_CommodeU_48" position={[-0.185, 20.834, -3.462]}>
                  <group name="CommodeDrawerU_47" position={[0, -0.834, -0.931]}>
                    <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Commode} />
                  </group>
                </group>
                <group name="Socket_CommodeM_50" position={[-0.185, 20.576, -3.462]}>
                  <group name="CommodeDrawerM_49" position={[0, -0.576, -0.931]}>
                    <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Commode} />
                  </group>
                </group>
                <group name="Socket_CommodeL_52" position={[-0.185, 20.316, -3.462]}>
                  <group name="CommodeDrawerL_51" position={[0, -0.316, -0.931]}>
                    <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Commode} />
                  </group>
                </group>
                <group name="Socket_2DoorUpperR_54" position={[0.101, 22.193, -3.537]}>
                  <group name="2DoorUpperDoorR_53" position={[0.605, -0.443, -0.886]}>
                    <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials['2Door.Upper']} />
                  </group>
                </group>
                <group name="Socket_2DoorUpperL_56" position={[1.312, 22.193, -3.537]}>
                  <group name="2DoorUpperDoorL_55" position={[-0.606, -0.443, -0.886]}>
                    <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['2Door.Upper']} />
                  </group>
                </group>
                <group name="Socket_2DoorR_58" position={[3.007, 20.458, -3.353]}>
                  <group name="Socket_2DoorDoorR_57" position={[0.605, -0.458, -0.904]}>
                    <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials['2Door']} />
                  </group>
                </group>
                <group name="Socket_2DoorL_60" position={[3.007, 20.458, -2.141]}>
                  <group name="Socket_2DoorDoorL_59" position={[-0.606, -0.458, -0.904]}>
                    <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['2Door']} />
                  </group>
                </group>
                <group name="Socket_1DoorUpperL_62" position={[-0.57, 22.193, -3.537]}>
                  <group name="1DoorUpperLDoor_61" position={[0.275, -0.443, -0.887]}>
                    <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials['1Door.Upper']} />
                  </group>
                </group>
                <group name="Socket_1DoorL_64" position={[0.322, 20.456, -3.488]}>
                  <group name="1DoorLDoor_63" position={[0.275, -0.456, -0.904]}>
                    <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['1Door']} />
                  </group>
                </group>
                <group name="Sink_65" position={[1.597, 20, -4.393]}>
                  <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Sink} />
                </group>
                <group name="Pot#2_66" position={[3.611, 20.962, -2.325]} rotation={[Math.PI, -1.285, Math.PI]}>
                  <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Pot2} />
                </group>
                <group name="Pot_67" position={[3.622, 20.974, -1.47]} rotation={[-Math.PI, 1.556, -Math.PI]}>
                  <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material} />
                </group>
                <group name="Plate#1_68" position={[0.764, 20.851, -0.605]}>
                  <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Plate} />
                </group>
                <group name="Pan_69" position={[3.263, 20.974, -1.798]} rotation={[0, 0.448, 0]}>
                  <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_28} />
                </group>
                <group name="Oven_70" position={[3.911, 20, -1.637]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.Oven} />
                </group>
                <group name="Microwave_71" position={[3.574, 20.962, -4.092]} rotation={[0, -0.651, 0]}>
                  <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.Microwave} />
                </group>
                <group name="HorizontalUpper_72" position={[2.486, 21.75, -4.424]}>
                  <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Horizontal.Upper']} />
                </group>
                <group name="Fridge_73" position={[3.144, 20, 1.965]} rotation={[Math.PI, -0.956, Math.PI]}>
                  <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.Fridge} />
                </group>
                <group name="Corner_74" position={[3.911, 20, -4.393]}>
                  <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.Corner} />
                </group>
                <group name="Commode_75" position={[-0.185, 20, -4.393]}>
                  <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.Commode} />
                </group>
                <group name="CoffeeMaker_76" position={[3.632, 20.962, -3.154]} rotation={[Math.PI, -0.088, Math.PI]}>
                  <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.CoffeeMaker} />
                </group>
                <Select name="chair1" enabled={hover === "chair1" || obj.chair1}>
                  <group name="Chair#1_77" position={[-0.549, 20, -1.437]} rotation={[0, 0.08, 0]}>?
                    <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.Chair} />
                  </group>
                </Select>
                <group name="2DoorUpper_78" position={[0.706, 21.75, -4.424]}>
                  <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['2Door.Upper']} />
                </group>
                <group name="2Door_79" position={[3.911, 20, -2.748]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['2Door']} />
                </group>
                <group name="1DoorUpperL_80" position={[-0.295, 21.75, -4.424]}>
                  <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['1Door.Upper']} />
                </group>
                <group name="1DoorL_81" position={[0.597, 20, -4.393]}>
                  <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['1Door']} />
                </group>
                <Select name="chair2" enabled={hover === "chair2" || obj.chair2} >
                  <group name="Chair#2_82" position={[0.38, 20, -1.42]} rotation={[0, -0.207, 0]}>
                    <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.Chair} />
                  </group>
                </Select>
                <group name="Chair#3_83" position={[0.252, 20, 0.103]} rotation={[-Math.PI, 0.089, -Math.PI]}>
                  <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.Chair} />
                </group>
                <group name="Chair#4_84" position={[-0.549, 20, 0.135]} rotation={[-Math.PI, 0.021, -Math.PI]}>
                  <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.Chair} />
                </group>
                <group name="Chair#5_85" position={[1.061, 20, -0.599]} rotation={[0, -1.433, 0]}>
                  <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.Chair} />
                </group>
                <group name="Chair#6_86" position={[-1.204, 20, -0.612]} rotation={[-Math.PI, 1.545, -Math.PI]}>
                  <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Chair} />
                </group>
                <group name="Socket_1Door_88" position={[2.872, 20.456, -3.488]} rotation={[-Math.PI, 0, 0]}>
                  <group name="1DoorDoor_87" position={[-0.275, 0.456, 0.904]}>
                    <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials['1Door']} />
                  </group>
                </group>
                <group name="1Door_89" position={[2.597, 20, -4.393]}>
                  <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials['1Door']} />
                </group>
                <group name="Socket_1DoorUpper_91" position={[1.981, 22.193, -3.537]} rotation={[-Math.PI, 0, 0]}>
                  <group name="1DoorUpperDoor_90" position={[-0.275, 0.443, 0.887]}>
                    <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['1Door.Upper']} />
                  </group>
                </group>
                <group name="1DoorUpper_92" position={[1.706, 21.75, -4.424]}>
                  <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['1Door.Upper']} />
                </group>
                <group name="Plate#2_93" position={[0.287, 20.851, -0.996]}>
                  <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Plate} />
                </group>
                <group name="Plate#4_94" position={[-0.454, 20.851, -1.017]}>
                  <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.Plate} />
                </group>
                <group name="Plate#6_95" position={[-0.533, 20.851, -0.255]}>
                  <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.Plate} />
                </group>
                <group name="Plate#3_99" position={[2.349, 20.962, -3.953]}>
                  <group name="Plate#31_96" position={[0, 0.012, 0]}>
                    <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.Plate} />
                  </group>
                  <group name="Plate#32_97" position={[0, 0.025, 0]}>
                    <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.Plate} />
                  </group>
                  <group name="Plate#33_98" position={[0, 0.037, 0]}>
                    <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.Plate} />
                  </group>
                  <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.Plate} />
                </group>
                <group name="Plate#5_100" position={[0.321, 20.851, -0.232]}>
                  <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.Plate} />
                </group>
                <group name="ExtractorHood_101" position={[3.941, 21.962, -1.637]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.ExtractorHood} />
                </group>
                <group name="Curtain#2_1" position={[0.657, -0.442, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                  <group name="Curtain#21_0">
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Curtain1.1']} />
                  </group>
                  <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Curtain} />
                </group>
                <group name="Floor_2" rotation={[-Math.PI, 0, -Math.PI]} scale={2.075}>
                  <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Floor} />
                </group>
                <group name="Roof_3" rotation={[-Math.PI, 0, -Math.PI]}>
                  <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Roof} />
                </group>
                <group name="Tile_4" rotation={[-Math.PI, 0, -Math.PI]} scale={2.075}>
                  <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Tile} />
                </group>
                <group name="Wall#1_5" rotation={[-Math.PI, 0, -Math.PI]} scale={2.075}>
                  <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Walls} />
                </group>
                <group name="Window#2_8" position={[0.657, -0.39, 0]}>
                  <group name="Window#2Glass_6">
                    <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Glass.001']} />
                  </group>
                  <group name="Window#2Wood_7">
                    <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Window} />
                  </group>
                  <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Window} />
                </group>
                <group name="Window#1_11" position={[0, -0.39, -0.476]} rotation={[0, -Math.PI / 2, 0]}>
                  <group name="Window#1Glass_9">
                    <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Glass.001']} />
                  </group>
                  <group name="Window#1Wood_10">
                    <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Window} />
                  </group>
                  <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Window} />
                </group>
                <group name="Curtain#1_13" position={[-0.505, -0.442, 2.842]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="Curtain#11_12">
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Curtain1.1']} />
                  </group>
                  <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Curtain} />
                </group>
              </Select>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/3dModel/kitchen/scene.gltf")
