/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dModel/toy/scene.gltf 
Author: PolyCube (https://sketchfab.com/ItsPolyCube)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/discord-wumpus-mascot-3d-model-7ff6ca221cd44381850984923804ebad
Title: Discord - Wumpus Mascot 3D Model
*/
"use client";
import React from "react";
import { useGLTF } from "@react-three/drei";

export function Toy(props) {
  const { nodes, materials } = useGLTF("/3dModel/toy/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -0.012, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-4.924, -0.322, 0.598]}
            rotation={[0.012, -0.176, -0.039]}
            scale={[0.689, 0.351, 0.254]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-4.837, -1.698, -0.024]}
            rotation={[0, -0.514, 0]}
            scale={[1.179, 0.94, 0.982]}
          >
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["Material.001"]}
            position={[-3.952, 0.088, 0.654]}
            rotation={[0.012, -0.176, -0.039]}
            scale={[0.232, 0.276, 0.232]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials["Material.002"]}
            position={[-3.062, 0.037, 0.113]}
            rotation={[0.012, -0.176, -0.039]}
            scale={[0.313, 0.505, 0.165]}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials["Material.002"]}
            position={[-6.451, 0.179, -0.488]}
            rotation={[-3.129, 0.176, -3.103]}
            scale={[0.339, 0.505, 0.165]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials["Material.001"]}
            position={[-5.844, 0.168, 0.32]}
            rotation={[0.012, -0.176, -0.039]}
            scale={[0.232, 0.264, 0.232]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials["Material.005"]}
            position={[-4.724, 1.228, -0.168]}
            rotation={[-0.002, -0.505, -0.044]}
            scale={[0.283, 0.043, 0.391]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials["Material.002"]}
            position={[-4.56, -1.878, -0.725]}
            rotation={[0, -0.376, 0]}
            scale={0.179}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials["Material.002"]}
            position={[-4.746, -1.7, 0.013]}
            rotation={[0.088, -0.518, 0.092]}
            scale={[1.179, 0.94, 0.982]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials["Material.002"]}
            position={[-4.815, -1.698, -0.015]}
            rotation={[0, -0.514, 0]}
            scale={[1.179, 0.94, 0.982]}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials["Material.002"]}
            position={[-4.888, -1.698, -0.044]}
            rotation={[0, -0.514, 0]}
            scale={[1.179, 0.94, 0.982]}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials["Material.002"]}
            position={[-4.837, -1.733, -0.024]}
            rotation={[-0.001, -0.514, -0.004]}
            scale={[1.179, 0.94, 0.982]}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials["Material.002"]}
            position={[-4.758, -1.693, -0.275]}
            rotation={[0.011, -0.314, -0.012]}
            scale={[1.179, 0.94, 0.982]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dModel/toy/scene.gltf");
